import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://shop.hersheys.com/home');
  await page.getByRole('button', { name: 'Accept All Cookies' }).click();
  await page.getByRole('button', { name: 'CHOCOLATE & CANDY' }).click();
  await page.getByRole('link', { name: 'JOLLY RANCHER Freeze Dried' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'My Cart' }).click();
  await page.getByRole('img', { name: 'Image of JOLLY RANCHER Freeze' }).click();
  await page.getByText('JOLLY RANCHER Freeze Dried').first().click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.locator('#email-guest').click();
  await page.locator('#email-guest').fill('testerramit@gmail.com');
  await page.getByRole('button', { name: 'Next: Shipping' }).click();
  await page.getByRole('textbox', { name: '* First Name * First Name' }).click();
  await page.getByRole('textbox', { name: '* First Name * First Name' }).fill('Tester');
  await page.getByRole('textbox', { name: '* First Name * First Name' }).press('Tab');
  await page.getByRole('textbox', { name: '* Last Name * Last Name' }).fill('Test');
  await page.getByRole('textbox', { name: '* Last Name * Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: '* Address 1 * Address' }).fill('Test 123');
  await page.getByRole('textbox', { name: '* Address 1 * Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address 2 Address' }).press('Tab');
  await page.getByRole('textbox', { name: '* City * City' }).fill('Test city');
  await page.getByRole('textbox', { name: '* City * City' }).press('Tab');
  await page.getByLabel('State * Continental US').selectOption('IA');
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).click();
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).fill('5544641');
  await page.getByRole('textbox', { name: '* Phone Number * Phone Number' }).click();
  await page.getByRole('textbox', { name: '* Phone Number * Phone Number' }).fill('46');
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).click();
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).fill('554464');
  await page.getByRole('textbox', { name: '* Phone Number * Phone Number' }).click();
  await page.getByRole('textbox', { name: '* Phone Number * Phone Number' }).fill('46564564564654564');
  await page.getByRole('button', { name: 'Next: Payment' }).click();
  await page.getByRole('button', { name: 'Confirm Address' }).click();
  await page.getByRole('button', { name: 'Next: Payment' }).click();
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).click();
  await page.getByRole('textbox', { name: '* ZIP Code * ZIP Code' }).fill('55446');
  await page.getByRole('button', { name: 'Next: Payment' }).click();
  await page.getByText('Shipping Address:').nth(1).click();
  await page.locator('div').filter({ hasText: /^46564564564654564$/ }).click();
  await page.locator('iframe[name="__privateStripeFrame1353"]').contentFrame().locator('.CardField-restWrapper').click();
  await page.locator('iframe[name="__privateStripeFrame1353"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).click();
  await page.locator('#card-element').click();
  await page.locator('iframe[name="__privateStripeFrame1353"]').contentFrame().locator('.CardField-restWrapper').click();
  await page.locator('iframe[name="__privateStripeFrame1353"]').contentFrame().getByRole('textbox', { name: 'Credit or debit card number' }).fill('4455 4654 6546 54655');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => { });
  });
  await page.getByRole('button', { name: 'Next: Review Order' }).click();
  await page.getByText('JOLLY RANCHER Freeze Dried').nth(1).click();
});